targets:
  $default:
    builders:
      freezed:freezed:
        enabled: true
        generate_for:
          include:
            - lib/data/models/**.dart
            - lib/domain/models/**.dart
            - lib/presentation/**_event.dart
            - lib/presentation/**_bloc.dart
            - lib/presentation/**_cubit.dart
        options:
          format: true
          makeCollectionsUnmodifiable: false
          # legacy
          map: false
          maybeMap: false
          mapOrNull: false
          when: false
          maybeWhen: false
          whenOrNull: false
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/data/models/**.dart
            - lib/domain/models/**.dart
      auto_route_generator:auto_route_generator:
        enabled: true
        generate_for:
          include:
            - lib/presentation/router/router.dart
            - lib/presentation/**_screen.dart
      auto_route_generator:auto_router_generator:
        enabled: true
        generate_for:
          include:
            - lib/presentation/router/router.dart
      flutter_gen_runner:
        enabled: true
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          include:
            - lib/data/repositories/**
            - lib/data/services/**
            - lib/domain/**_manager.dart
            - lib/presentation/**_bloc.dart
            - lib/presentation/**_cubit.dart
      injectable_generator:injectable_config_builder:
        enabled: true
        generate_for:
          include:
            - lib/core/injector/injector.dart
