name: secure_storage
description: A Storage implementation backed by flutter_secure_storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.13.0
  flutter: ^3.47.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^11.0.0
