#!/usr/bin/env bash

# export PATH="$PATH:/path/to/flutter" (fvm or global path)

# Sort imports

echo -e "Checking imports...\n"

if ! dart run tidy_imports --exit-if-changed; then
  echo -e "\nSorting imports...\n"
  dart run tidy_imports
  echo -e "\nOops, some imports weren't sorted. Check your unstaged changes or try to resolve the issues manually.\n"
  exit 1
fi

# Analyze code

# output=$(flutter analyze --no-fatal-infos)
# status=$?
# echo "$output" | grep -E "error •|warning •"

flutter analyze .
status=$?

if [ "$status" = 0 ] ; then
  echo -e "\nPerfecto!!!"
  exit 0
else
  echo -e "\nOops, something is wrong. Trying to automatically fix the issues...\n"
  dart fix --apply
  echo -e "\nCheck your unstaged changes or try to resolve the issues manually..\n"
  exit 1
fi