include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - bricks/**
    - '**/*.g.dart'
    - '**/*config.dart'
    - '**/*.freezed.dart'
    - '**/*.gen.dart'
    - '**/*.gr.dart'
  errors:
    invalid_annotation_target: ignore
