name: {{project_name}}
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  

  #easy_localization and generator
  easy_localization: ^3.0.1
  stx_easy_localization_generator: ^1.0.1

  #helps create form validation
  stx_flutter_form_bloc: ^0.0.3

  #routing
  auto_route: ^4.0.1

  #DI
  get_it: ^7.2.0
  injectable: ^1.5.3

  #splash screen
  flutter_native_splash: ^2.2.1

  #configuration
  flutter_dotenv: ^5.0.2

  #state management
  flutter_bloc: ^8.0.1
  provider: ^6.0.2

  #http client
  dio: ^4.0.6

  #local storage
  shared_preferences: ^2.0.15

  #helps generate dart models
  freezed_annotation: ^2.0.3

  #icons
  font_awesome_flutter: ^10.1.0

  #sort imports
  import_sorter: ^4.6.0

  #widgets
  cupertino_icons: ^1.0.4
  bouncing_widget: ^2.0.0
  tab_indicator_styler: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.2.0
  auto_route_generator: ^4.0.0
  injectable_generator: ^1.5.3
  freezed: ^2.0.3+1

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - resources/langs/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

flutter_gen:
  output: lib/styles/  # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enabled: true
    package_parameter_enabled: false

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo-short.png

import_sorter:
  comments: false
