name: {{project_name}}
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #splash screen
  flutter_native_splash: ^2.4.0

  #softonix core packages
  stx_bloc_base: ^0.5.1
  stx_flutter_form_bloc: ^2.3.0

  #state management
  provider: ^6.1.2
  flutter_bloc: ^8.1.5

  #dependency injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  #routing
  auto_route: ^8.1.3

  #a powerful Http client for Dart, which supports Interceptors, Global configuration, FormData,
  #Request Cancellation, File downloading, Timeout etc.
  dio: ^5.4.3+1
  fresh_dio: ^0.4.1
  dio_smart_retry: ^6.0.0

  #code generator for unions/pattern-matching/copy.
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  #easy_localization and generator
  easy_localization: ^3.0.7
  stx_easy_localization_generator: ^1.0.1

  #this package extends the native Iterable type with all of the LINQ methods that do not exist in native Dart
  darq: ^2.0.0

  #local storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  #icons
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

  #testing
  patrol: ^3.7.2
  patrol_finders: ^2.1.2
  mockito: ^5.4.4
  bloc_test: ^9.1.7

  #widgets
  bouncing_widget: ^2.0.0
  tab_indicator_styler: ^2.0.0
  extended_nested_scroll_view: ^6.2.1

  #other

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.5.0+1
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  freezed: ^2.5.3
  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0
  very_good_analysis: ^5.1.0

dependency_overrides:
  meta: ^1.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - resources/langs/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

flutter_gen:
  output: lib/styles/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml

import_sorter:
  comments: false
  ignored_files:
    - \.g\.dart$
    - \.config\.dart$
    - \.freezed\.dart$
    - \.gen\.dart$
    - \.gr\.dart$
    - \.mocks\.dart$

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo-short.png

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  image_path: "assets/images/app_icon.png"

patrol:
  app_name: {{#pascalCase}}{{project_name}}{{/pascalCase}}
  android:
    package_name: com.example.{{project_name}}
  ios:
    bundle_id: com.example.{{project_name}}
