// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_guidelines/test/unit_test/blocs/auth/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i4;
import 'package:flutter_guidelines/models/general_models.dart' as _i7;
import 'package:flutter_guidelines/models/index.dart' as _i3;
import 'package:flutter_guidelines/repositories/auth_repository.dart' as _i6;
import 'package:flutter_guidelines/repositories/user_repository.dart' as _i8;
import 'package:flutter_guidelines/services/http/http_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpClient_0 extends _i1.SmartFake implements _i2.HttpClient {
  _FakeHttpClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_1 extends _i1.SmartFake implements _i3.UserProfile {
  _FakeUserProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2<T1> extends _i1.SmartFake implements _i4.Response<T1> {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  @override
  _i2.HttpClient get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeHttpClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
        returnValueForMissingStub: _FakeHttpClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.HttpClient);

  @override
  _i5.Stream<_i7.AuthStatus> get authenticationStatus => (super.noSuchMethod(
        Invocation.getter(#authenticationStatus),
        returnValue: _i5.Stream<_i7.AuthStatus>.empty(),
        returnValueForMissingStub: _i5.Stream<_i7.AuthStatus>.empty(),
      ) as _i5.Stream<_i7.AuthStatus>);

  @override
  _i5.Future<void> signIn(
    String? userName,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            userName,
            password,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i8.UserRepository {
  @override
  _i2.HttpClient get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeHttpClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
        returnValueForMissingStub: _FakeHttpClient_0(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i2.HttpClient);

  @override
  _i5.Future<_i3.UserProfile> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_1(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_1(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i2.HttpClient {
  @override
  _i5.Stream<_i7.AuthStatus> get authenticationStatus => (super.noSuchMethod(
        Invocation.getter(#authenticationStatus),
        returnValue: _i5.Stream<_i7.AuthStatus>.empty(),
        returnValueForMissingStub: _i5.Stream<_i7.AuthStatus>.empty(),
      ) as _i5.Stream<_i7.AuthStatus>);

  @override
  _i5.Future<void> setToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearToken() => (super.noSuchMethod(
        Invocation.method(
          #clearToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i4.Response<T>> getR<T>(
    String? url, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getR,
          [url],
          {
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #getR,
            [url],
            {
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #getR,
            [url],
            {
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response<T>>);

  @override
  _i5.Future<T> get<T>(
    String? url, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #get,
                  [url],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #get,
                [url],
                {
                  #queryParameters: queryParameters,
                  #options: options,
                },
              ),
            ),
        returnValueForMissingStub: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #get,
                  [url],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #get,
                [url],
                {
                  #queryParameters: queryParameters,
                  #options: options,
                },
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<_i4.Response<T>> postR<T>(
    String? url, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postR,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #postR,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #postR,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response<T>>);

  @override
  _i5.Future<T> post<T>(
    String? url, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #post,
                [url],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                },
              ),
            ),
        returnValueForMissingStub: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #post,
                [url],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                },
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<_i4.Response<T>> putR<T>(
    String? url, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putR,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #putR,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #putR,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response<T>>);

  @override
  _i5.Future<T> put<T>(
    String? url, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #put,
                [url],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                },
              ),
            ),
        returnValueForMissingStub: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #put,
                [url],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                },
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<_i4.Response<T>> patchR<T>(
    String? url, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchR,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #patchR,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #patchR,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response<T>>);

  @override
  _i5.Future<T> patch<T>(
    String? url, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #patch,
                [url],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                },
              ),
            ),
        returnValueForMissingStub: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #patch,
                [url],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                },
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<_i4.Response<T>> deleteR<T>(
    String? url, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteR,
          [url],
          {
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i5.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #deleteR,
            [url],
            {
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i4.Response<T>>.value(_FakeResponse_2<T>(
          this,
          Invocation.method(
            #deleteR,
            [url],
            {
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response<T>>);

  @override
  _i5.Future<T> delete<T>(
    String? url, {
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #delete,
                [url],
                {
                  #queryParameters: queryParameters,
                  #options: options,
                },
              ),
            ),
        returnValueForMissingStub: _i9.ifNotNull(
              _i9.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                  },
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_3<T>(
              this,
              Invocation.method(
                #delete,
                [url],
                {
                  #queryParameters: queryParameters,
                  #options: options,
                },
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<_i4.Response<dynamic>> download(
    String? url,
    String? savePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            url,
            savePath,
          ],
        ),
        returnValue:
            _i5.Future<_i4.Response<dynamic>>.value(_FakeResponse_2<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              url,
              savePath,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i4.Response<dynamic>>.value(_FakeResponse_2<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              url,
              savePath,
            ],
          ),
        )),
      ) as _i5.Future<_i4.Response<dynamic>>);
}
