name: persistent_storage
description: A Storage implementation backed by shared_preferences.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.13.0
  flutter: ^3.47.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  storage:
    path: ../storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  shared_preferences_platform_interface: ^2.4.2
  very_good_analysis: ^11.0.0
